### ISSUE TITLE
raise_for_status argument is ignored

### ISSUE THREAD

**Issue by ilai-deutel** [pnuckowski/aioresponses#124]
Hi,

The `raise_for_status` argument can be passed to a [`ClientSession`](https://docs.aiohttp.org/en/stable/client_reference.html?highlight=raise_for_status#aiohttp.ClientSession) since aiohttp v2.0.0 and to individual [requests](https://docs.aiohttp.org/en/stable/client_reference.html?highlight=raise_for_status#aiohttp.ClientSession.request) since v3.4.0. aioresponses seems to ignore it.

The following code should raise a `ClientResponseError`, but it doesn't:

```python
loop = asyncio.get_event_loop()

# Start a session with the raise_for_status argument
session = aiohttp.ClientSession(raise_for_status=True)

with aioresponses() as m:
    m.get('http://example.com', status=500)
    loop.run_until_complete(session.get('http://example.com'))
```

If this is indeed a bug, I'm happy to submit a PR. I made changes to the code [here](https://github.com/ilai-deutel/aioresponses/commit/67bd41ee38c33a5cf713fd2bb611f3e7d0fc888c).

**Comment by pnuckowski** [comment]
Hi @ilai-deutel 
thanks for the issue :)

Feel free to submit PR, code looks good 👍
