### ISSUE TITLE
Only one request can be sent in an aioresponses() context？

### ISSUE THREAD

**Issue by yiyuhao** [pnuckowski/aioresponses#128]
I sent two same requests in an aioresponses() context, but the second failed:

`aiohttp.client_exceptions.ClientConnectionError: Connection refused: GET http://test.example.com`

 Here's my code:
```
import asyncio

import aiohttp
from aioresponses import aioresponses


def test_ctx():
    loop = asyncio.get_event_loop()
    session = aiohttp.ClientSession()
    with aioresponses() as m:
        m.get('http://test.example.com', payload=dict(foo='bar'))

        resp = loop.run_until_complete(session.get('http://test.example.com'))
        data = loop.run_until_complete(resp.json())

        assert dict(foo='bar') == data

        resp = loop.run_until_complete(session.get('http://test.example.com'))
        data = loop.run_until_complete(resp.json())

        assert dict(foo='bar') == data
```

The question is: 
Was it designed for some reasons? And what are these reasons?

**Comment by jllorencetti** [comment]
@yiyuhao based on this line [1] you probably need to pass `repeat` as `True`, something like:
```python
m.get('http://test.example.com', payload=dict(foo='bar'), repeat=True)
```

[1] https://github.com/pnuckowski/aioresponses/blob/master/aioresponses/core.py#L309

**Comment by yiyuhao** [comment]
> @yiyuhao based on this line [1] you probably need to pass `repeat` as `True`, something like:
> 
> ```python
> m.get('http://test.example.com', payload=dict(foo='bar'), repeat=True)
> ```
> 
> [1] https://github.com/pnuckowski/aioresponses/blob/master/aioresponses/core.py#L309


Thank you!  I apologize for my carelessness.
But can you tell me why the default value is False?

**Comment by blueyed** [comment]
I personally like `repeat=False` by default (more explicit).

When changing this it might be an idea to support a count there also, i.e. `repeat=3` would work three times.  This could then maybe even be used in the test teardown (automatically) to assert that it went down to 0 or something similar.
