### ISSUE TITLE
Add methods for check request data

### ISSUE THREAD

**Issue by antipooh** [pnuckowski/aioresponses#132]
Hello, can be added methods like "assert_called_once_with" from mock.Mock for check POST request?

**Comment by UncleGoogle** [comment]
@antipooh can you reopen the issue? Implementation was not shipped yet

**Comment by antipooh** [comment]
Code not in master

**Comment by antipooh** [comment]
No code in master

**Comment by matthewgoslett** [comment]
Are we ever going to be able to test POST or PATCH data, or is their a recommended or suggested workaround here?

I see [@SukiCZ](https://github.com/SukiCZ) did some work here a few years back: https://github.com/pnuckowski/aioresponses/pull/133
