### ISSUE TITLE
Provide a way to mock out response cookies

### ISSUE THREAD

**Issue by unmade** [pnuckowski/aioresponses#155]
Hi there!

First of all thanks for the great library and your efforts!

### Problem

It seems that now there is no way to mock out response cookies. I initially tried to set cookies by adding "Set-Cookie" to response headers, however this also doesn't work (neither for ``headers`` argument of the `aioresponses.add` method, nor using callback).

In `aiohttp.ClientResponse` cookies are loaded from headers in its `start` method [source](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L820-L827)

However aioresponses don't call this method and just set headers without loading cookies. 

### Workaround

My current workaround to set cookies looks like that:

```python
from aioresponses import CallbackResult
from aiohttp import ClientResponse, hdrs


async def callback(url, **kwargs):
    class Response(ClientResponse):
        @property
        def _headers(self):
            return self.__headers

        @_headers.setter
        def _headers(self, value):
            self.__headers = value
            for hdr in value.getall(hdrs.SET_COOKIE, ()):
                self.cookies.load(hdr)

    return CallbackResult(
        response_class=Response,
        status=200,
        headers=headers,
        ...
    )
```

### Proposal/Solution

So my proposal is to extract cookies from headers somewhere [here](https://github.com/pnuckowski/aioresponses/blob/master/aioresponses/core.py#L158-L164). Alternatively, we can make additional `cookies` parameter for `aioresponses` method. 

I personally think the first variant will be better as it covers most of the use cases, while adding a new argument to a method requires more work and had more ambiguity.  

What do you think about it? I'll be happy to contribute with that

**Comment by unmade** [comment]
BTW, it doesn't relate to the problem directly, but it also seems the type hint for `response_class` should be `Type[ClientResponse]` instead of just `ClientResponse`

**Comment by 0xf10413** [comment]
Hi,
thanks for the fix! Do you know when it will be available on pypi ?
