### ISSUE TITLE
0.7.0 release depends on aysnctest for Python <3.8, but does not declare it to pip

### ISSUE THREAD

**Issue by TBBle** [pnuckowski/aioresponses#172]
We saw the following failure in our Python 3.7-based unit tests when a new build pulled in aioresponses 0.7.0:

```
==================================== ERRORS ====================================
_______________ ERROR collecting tests/test_director_manager.py ________________
ImportError while importing test module '/builds/kepler/director-manager/tests/test_director_manager.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/site-packages/aioresponses/compat.py:14: in <module>
    from unittest import IsolatedAsyncioTestCase, skipIf
E   ImportError: cannot import name 'IsolatedAsyncioTestCase' from 'unittest' (/usr/local/lib/python3.7/unittest/__init__.py)

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_director_manager.py:12: in <module>
    from aioresponses import CallbackResult, aioresponses
/usr/local/lib/python3.7/site-packages/aioresponses/__init__.py:2: in <module>
    from .core import CallbackResult, aioresponses
/usr/local/lib/python3.7/site-packages/aioresponses/core.py:23: in <module>
    from .compat import (
/usr/local/lib/python3.7/site-packages/aioresponses/compat.py:29: in <module>
    from asynctest import fail_on, skipIf
E   ModuleNotFoundError: No module named 'asynctest'
----- generated xml file: /builds/kepler/director-manager/test_results.xml -----
```

I believe this is because adfb65038caebce3d621bfe28dd3a6d0e5542ffe from #168 made `asynctest` a hard-requirement for Python 3.7 and earlier, added it to _requirements-dev.txt_ instead of _requirements.txt_. `pbr` consumes the latter for generating the requirements exposed and fulfilled by pip.

Test still pass on Python 3.7 because _tox.ini_ installs _requirements-dev.txt_ directly, rather than _requirements.txt_ plus any test-specific requirements, so the testing environment is not "clean", compared to what a user experiences.

Also, the main _README.md_, _requirements.txt_ and _tox.ini_ still lists support for "Python 3.5.3+" and "aiohttp>=2.0.0,<4.0.0".

**Comment by TBBle** [comment]
It's possible this was overlooked because most aioresponses users on Python 3.7 are using `asynctest` with `unittest`.

In our tests, we're using `pytest-aiohttp` with `pytest` to support async test-cases, so we don't have `asynctest` installed by our own requirements.txt.

**Comment by TBBle** [comment]
Thinking about it, why does `aioresponses.compat` provide `AsyncTestCase`, `skipIf` and `fail_on`? Do we really expect users of aioresponses to be pulling those in from this module, or are they likely to only be used for aioresponses's own tests.

**Comment by pnuckowski** [comment]
hi @TBBle 

new version released that fixes that issue. 
Sorry for trouble, I overlooked that aspect :/
