### ISSUE TITLE
ModuleNotFoundError: No module named 'asynctest'

### ISSUE THREAD

**Issue by pbelskiy** [pnuckowski/aioresponses#176]
Hello, you missed to add asynctest to your requirements.txt

```python
.tox/pytest/lib/python3.7/site-packages/aioresponses/compat.py:29: in <module>
48
    from asynctest import fail_on, skipIf
49
E   ModuleNotFoundError: No module named 'asynctest'
```

**Comment by vchetyrkine** [comment]
I believe this is linked to https://github.com/pnuckowski/aioresponses/issues/172 ?

**Comment by pnuckowski** [comment]
Hi @pbelskiy 
new release fixes that problem. Sorry for trouble, it was my mistake :/
