### ISSUE TITLE
`py.typed`?

### ISSUE THREAD

**Issue by AustinScola** [pnuckowski/aioresponses#191]
I noticed that `aioresponses` has type annotations but does not package a `py.typed` file? Is there a reason for this? If not, it would be helpful to include such a file so that code which uses `aioresponses` can be type checked easily.

Along those lines, the classifier `Typing :: Typed` should probably be added.

**Comment by pbelskiy** [comment]
https://github.com/pnuckowski/aioresponses/pull/193
