### ISSUE TITLE
[BUG aiohttp 3.9] await self._writer TypeError: object Mock can't be used in 'await' expression

### ISSUE THREAD

**Issue by JCHacking** [pnuckowski/aioresponses#247]
It seems that with aiohttp 3.9 the library will stop working:
See comment in aiohttp release 3.9 issue > https://github.com/aio-libs/aiohttp/issues/7675#issuecomment-1804524374

**Comment by JCHacking** [comment]
I see that the solution that I proposed is merge to main, so it would only be necessary to publish it with a release that is published in pypi

**Comment by JCHacking** [comment]
I see that the solution that I proposed is merge to main, so it would only be necessary to publish it with a release that is published in pypi

**Comment by arossert** [comment]
I'm also waiting for this fix 🙏

**Comment by mmalka87** [comment]
why not pin to a specific version per release?

**Comment by arossert** [comment]
I'm getting `aiohttp` from another module and not importing it into my code directly.
Currently, I fixed it in the `setup.py` anyways for now until this will have a new release

**Comment by JCHacking** [comment]
> why not pin to a specific version per release?

I don't see a logical way to do it, since this is an external dependency to aiohttp and compatible with multiple versions of aiohttp.

There is no way to

**Comment by JCHacking** [comment]
@pnuckowski 
Can you generate a new release with this correction? I see a lot of people waiting for it

Thank You!!!

**Comment by pnuckowski** [comment]
@JCHacking released as 0.7.6
