### ISSUE TITLE
release is version 0.7.4 however latest tag is 0.7.6

### ISSUE THREAD

**Issue by nivhanin** [pnuckowski/aioresponses#255]
Why is that? 

Do we going to release new version soon? or is this project dead?

**Comment by gaby** [comment]
Ping @pnuckowski

**Comment by pnuckowski** [comment]
https://pypi.org/project/aioresponses/0.7.6/ version is released @nivhanin

**Comment by gaby** [comment]
@pnuckowski Can we get 0.7.7 with the fixes from #254

**Comment by gaby** [comment]
@pnuckowski Any chance of getting v0.7.7

**Comment by nivhanin** [comment]
thanks 🥳
