### ISSUE TITLE
Support for throwing an exception

### ISSUE THREAD

**Issue by alefteris** [pnuckowski/aioresponses#56]
Does aioresponses support throwing an exception, similar to what https://github.com/getsentry/responses provides?

For example something like:
```python

class MyError(Exception):
    pass

with aioresponses() as m:
    m.get('http://test.example.com', body=MyError())
```

**Comment by pnuckowski** [comment]
Hi @alefteris currently there is no possibility to raise an error, but I prepared PR with this feature. Shortly it will be merged and released.
