### ISSUE TITLE
Release 0.1.5

### ISSUE THREAD

**Issue by rrader** [pnuckowski/aioresponses#65]
Can you please release the 0.1.5 version with commit https://github.com/pnuckowski/aioresponses/commit/867782faf7c17484dd5a6d950994ab503878be86 -  fix startswith error 
It's important fix, package can't be used without it.

Thank you.

**Comment by decaz** [comment]
@pnuckowski Could you merge #66 and release v0.1.5 ?

**Comment by pnuckowski** [comment]
@rrader @decaz Thanks for contribution :) 

New version released 💥 ✨ 🎉
