### ISSUE TITLE
Mock timeout?

### ISSUE THREAD

**Issue by leplatrem** [pnuckowski/aioresponses#68]
Thanks for the awesome library. Installed, used it, loved it. Combined with `asynctest` it's very pleasant.

Just in case you're interested with feature ideas, I think mocking request timeouts would fall in the scope. In order to test stuff like that: 

```py
# Code example
async with session.get(url, headers=headers, timeout=timeout) as response:
    return await response.json()
```

or 

```py
with async_timeout.timeout(timeout):
    async with session.get(url, headers=headers, timeout=None) as response:
        return await response.json()
```

It could be by specifying a `delay` parameter to `aioresponses.add(...)`, that would then rely on `await asyncio.sleep()` for example.

What do you think?

**Comment by pnuckowski** [comment]
Hi @leplatrem 
Just week ago i have been thinking to add this feature as You propose to aioresponses :)

I will implement this in couple of days, need to look at timeout in depth, also Im on europython right now :)

**Comment by Natim** [comment]
I am also looking for a similar feature.

**Comment by leplatrem** [comment]
This is the work-around I had (there may be shorter solutions):

```python
class LongResponse:
    def __init__(*args, **kwargs):
        pass

    async def __call__(self, *args, **kwargs):
        return self

    async def __aenter__(self, *args):
        return self

    async def __aexit__(self, *args):
        pass

    async def json(self):
        return await asyncio.sleep(10000)


class MyFetchFunc(asynctest.TestCase):
    async def setUp(self):
        self.session = aiohttp.ClientSession(loop=self.loop)
        self.addCleanup(self.session.close)

    async def test_raises_timeout_response(self):
        with asynctest.patch.object(self.session, "get", LongResponse):
            with self.assertRaises(asyncio.TimeoutError):
                await my_fetch_func(self.session, "http://server.org", timeout=0.1)
```

**Comment by Natim** [comment]
Nice thanks

**Comment by pnuckowski** [comment]
Feature is partially implemented.
Added timeout argument. Under the neath it is equal to
```python
mock.get('http://example.com', timeout=True)
# is equal to 
mock.get('http://example.com', exception=asyncio.TimeoutError('Connection timeout'))
```

Actually i started with real support for timeout and event implement it (using real asyncio.sleep())
and start writing tests for cases where aiohttp is used with `async_timeout` and `aiohttp.helpers.Timeout()`.

But starting from aiohttp 3.4 timeout is made completely different. Not as context manager that cancel's Task, but using `ClientTimeout`.

To make this work it will require more work on `aioresponses` side ( more complex mocking and it could be hard to maintain backward compatibility ) not sure if implementing this gives us some real benefits.
Priority for me is to not make `aioresponses` code heavy and hard to read.


Maybe later on will try to implement it the right way, but for now I'm closing the issue.

**Comment by colinpade** [comment]
Just writing to say thank you. This helped me today 👏
