### ISSUE TITLE
Update for aiohttp v3.0 release

### ISSUE THREAD

**Issue by achimnol** [pnuckowski/aioresponses#88]
It seems to have been broken since aio-libs/aiohttp#2556, as I get the following error in my test codes using aioresponses:

```
>       self.resp.content = StreamReader()
E       TypeError: __init__() missing 1 required positional argument: 'protocol'
```

**Comment by achimnol** [comment]
Ooops, I just found that #87 is already there! :+1:
So the choice between #87 or #89 would depend on the author's decision on whether to drop v1 support or not. 🙄

**Comment by pnuckowski** [comment]
Close this issue. Pr was merged.
