### ISSUE TITLE
Add mocked requests count or mocked requests left

### ISSUE THREAD

**Issue by pnuckowski** [pnuckowski/aioresponses#9]
Give user ability to check if all mocked request was called

**Comment by kowalski** [comment]
https://github.com/pnuckowski/aioresponses/pull/55

Instead of checking what is left, I record all the calls. IMO this is more usefull, because I can use it to make assertations on what my code pass to the external server

**Comment by pnuckowski** [comment]
Closing issue.

Implemented in aioresponses==0.1.4, thanks @kowalski
